#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash scripts/run_solidity_three_rounds.sh

Environment overrides:
  MODEL=qwen2.5-14b-instruct
  PROVIDER=auto
  STRATEGY=indict_llama
  DATA_PATH=data/solidity_fsm_testable_10.json
  EXPERIMENT=fsm_testable10_structured_retry
  OPENAI_RESPONSES_URL=https://gmn.chuangzuoli.com/v1/responses
  OPENAI_BASE_URL=https://gmn.chuangzuoli.com/v1
  DEEPSEEK_API_BASE=https://api.deepseek.com
  PYTHON_BIN=python
  OVERRIDE=1
  DEBUG=1

Required:
  DASHSCOPE_API_KEY or QWEN_API_KEY for Qwen
  OPENAI_API_KEY for OpenAI
  DEEPSEEK_API_KEY for DeepSeek

Outputs:
  solidity_<MODEL>/<STRATEGY>_<EXPERIMENT>_round1
  solidity_<MODEL>/<STRATEGY>_<EXPERIMENT>_round2
  solidity_<MODEL>/<STRATEGY>_<EXPERIMENT>_round3
  solidity_<MODEL>/<STRATEGY>_<EXPERIMENT>_round3/summary.json
  solidity_<MODEL>/<STRATEGY>_<EXPERIMENT>_round3/summary.csv
  solidity_<MODEL>/<STRATEGY>_<EXPERIMENT>_round3/summary.md
  solidity_<MODEL>/<STRATEGY>_<EXPERIMENT>_round3/summary_round_comparison.csv
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

model="${MODEL:-qwen2.5-14b-instruct}"
provider="${PROVIDER:-auto}"
strategy="${STRATEGY:-indict_llama}"
data_path="${DATA_PATH:-data/solidity_fsm_testable_10.json}"
experiment="${EXPERIMENT:-fsm_testable10_structured}"
python_bin="${PYTHON_BIN:-python}"
override="${OVERRIDE:-1}"
debug="${DEBUG:-0}"

if [[ "$provider" == "openai" || "$model" == openai:* || "$model" == openai-* || "$model" == gpt* ]]; then
  if [[ -z "${OPENAI_API_KEY:-}" ]]; then
    echo "ERROR: set OPENAI_API_KEY before running OpenAI generation." >&2
    exit 2
  fi
elif [[ "$provider" == "deepseek" || "$model" == deepseek:* || "$model" == deepseek* ]]; then
  if [[ -z "${DEEPSEEK_API_KEY:-}" ]]; then
    echo "ERROR: set DEEPSEEK_API_KEY before running DeepSeek generation." >&2
    exit 2
  fi
elif [[ -z "${DASHSCOPE_API_KEY:-}" && -z "${QWEN_API_KEY:-}" ]]; then
  echo "ERROR: set DASHSCOPE_API_KEY or QWEN_API_KEY before running Qwen generation." >&2
  exit 2
fi

if [[ ! -f "$data_path" ]]; then
  echo "ERROR: dataset not found: $data_path" >&2
  exit 2
fi

suffix_prefix="_${experiment}"
output_root="solidity_${model}"
round1_dir="${output_root}/${strategy}${suffix_prefix}_round1"
round2_dir="${output_root}/${strategy}${suffix_prefix}_round2"
round3_dir="${output_root}/${strategy}${suffix_prefix}_round3"

common_args=(
  run.py
  --task solidity
  --model "$model"
  --provider "$provider"
  --strategy "$strategy"
  --data_path "$data_path"
)

if [[ "$override" =~ ^(1|true|yes|on)$ ]]; then
  common_args+=(--override)
fi

if [[ "$debug" =~ ^(1|true|yes|on)$ ]]; then
  common_args+=(--debug)
fi

verify_latest_code_output() {
  local result_dir="$1"
  local round_number="$2"

  "$python_bin" - "$result_dir" "$round_number" <<'PY'
import json
import sys
from pathlib import Path

result_dir = Path(sys.argv[1])
round_number = int(sys.argv[2])
sample_path = result_dir / "0.json"

if not sample_path.exists():
    raise SystemExit(f"ERROR: expected smoke-check file is missing: {sample_path}")

record = json.loads(sample_path.read_text(encoding="utf-8"))
required = [
    "initial_structured_feedback",
    "structured_feedback",
    "mid_structured_feedback",
    "final_structured_feedback",
]
missing = [key for key in required if key not in record]
if missing:
    raise SystemExit(
        "ERROR: result does not look generated by the latest structured-feedback code. "
        f"Missing keys in {sample_path}: {', '.join(missing)}"
    )

if round_number > 1 and "previous_structured_feedback" not in record:
    raise SystemExit(
        "ERROR: previous_structured_feedback is missing. "
        "The next-round feedback chain is not active."
    )

metrics = record.get("execution_metrics") or {}
if "slither_findings" not in metrics:
    raise SystemExit(
        "ERROR: execution_metrics.slither_findings is missing. "
        "The latest Solidity backend is not active."
    )

print(f"[ok] latest-code fields found in {sample_path}")
PY
}

run_round() {
  local round_number="$1"
  local suffix="${suffix_prefix}_round${round_number}"
  local prev_dir="${2:-}"

  echo
  echo "=== Solidity generation round ${round_number}/3 ==="
  echo "suffix: ${suffix}"
  if [[ -n "$prev_dir" ]]; then
    echo "prev_trial: ${prev_dir}"
    "$python_bin" "${common_args[@]}" --suffix "$suffix" --prev_trial "$prev_dir"
  else
    "$python_bin" "${common_args[@]}" --suffix "$suffix"
  fi
}

echo "Experiment config:"
echo "  model:      $model"
echo "  provider:   $provider"
echo "  strategy:   $strategy"
echo "  data_path:  $data_path"
echo "  experiment: $experiment"
echo "  output:     $output_root"
echo "  override:   $override"
echo "  debug:      $debug"

run_round 1
verify_latest_code_output "$round1_dir" 1

run_round 2 "$round1_dir"
verify_latest_code_output "$round2_dir" 2

run_round 3 "$round2_dir"
verify_latest_code_output "$round3_dir" 3

echo
echo "=== Summarizing round 3 and auto-detecting round comparison ==="
"$python_bin" scripts/summarize_solidity_results.py \
  --dataset "$data_path" \
  --results-dir "$round3_dir" \
  --output-prefix "$round3_dir/summary"

echo
echo "[ok] All rounds and summary completed."
echo "Round 1: $round1_dir"
echo "Round 2: $round2_dir"
echo "Round 3: $round3_dir"
echo "Summary:"
echo "  $round3_dir/summary.json"
echo "  $round3_dir/summary.csv"
echo "  $round3_dir/summary.md"
echo "  $round3_dir/summary_round_comparison.csv"
